### ISSUE TITLE
Redo ALL the syntax definitions

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/PackageDev#67]
They've needed a new version in a long time, so once `.sublime-syntax` gets out of dev, it sounds like a good idea to start working on this.

Because I do not intend to also include the old files, this would mark a backwards incompatible release and the current version would be split off into a branch/tag. (This has already happened.)

---

Current progress:

- [x] Sublime Text Build System (#125)
- [x] Sublime Text Commands (#124)
- [x] Sublime Text Completions (#123)
- [x] Sublime Text Keymap (#90)
- [x] Sublime Text Macro (#127)
- [x] Sublime Text Menu (new) (#126)
- [x] Sublime Text Mousemap (#122)
- [x] Sublime Text Project (new) (2c3b3d9c70d304cda7339f000099cb42122c9f95)
- [x] Sublime Text Settings (#113)
- [x] Sublime Text Snippet (#88)
- [x] Sublime Text Syntax Definition (new) (be29b0732965b8b9549c88f7f72ec28e3e209879)
- [x] TextMate Preferences Textmate (new) (#88)
- [ ] ~~TextMate Syntax Definition (JSON)~~ (this is legacy stuff and likely not happening)
- [ ] ~~TextMate Syntax Definition (YAML)~~ (this is legacy stuff and likely not happening)

Sub-syntaxes:

- [x] Scope selector (#88)
- [x] Oniguruma Regualar Expression (be29b0732965b8b9549c88f7f72ec28e3e209879)
- [x] Raw Snippets (#88)
- [x] Escaped Regular Expression (Boost) (f3784074519d1aa8f1ce863a6edc650c097f9d04)

**Comment by evandrocoan** [comment]
There is also this problem on `sublime-keymap`:
```
    { "keys": ["A"], "command": "open_auto_completion" }
```

The upper case key `"A"` alone is a valid case and I using it normally, but it is marked as invalid:

![image](https://cloud.githubusercontent.com/assets/5332158/26595716/bb207886-4542-11e7-978b-39fbefba51d4.png)

**Comment by FichteFoll** [comment]
Interesting. They certainly aren't valid with modifiers but it seems like for single characters anything goes (if this does indeed work, which I can't verify right now). 

Please open a new issue for things like this next time, though.

**Comment by FichteFoll** [comment]
With f3784074519d1aa8f1ce863a6edc650c097f9d04, the last remaining non-legacy syntax definition has been rewritten or added.

Since I don't care about the legacy syntaxes anymore (for JSON-tmLanguage and YAML-tmLanguage), they won't receive any feature updates and *may* only receive some bugfixing in the future, this is finally done after over half a year in the making.
